.\" This document is in the public domain.
.\" vim: fdm=marker
.
.\" FRONT MATTER {{{
.Dd Aug 20, 2014
.Os
.Dt GIT-MANTLE 1
.
.Sh NAME
.Nm git-mantle
.Nd Generate an overview of changes on a branch
.\" FRONT MATTER }}}
.
.\" SYNOPSIS {{{
.Sh SYNOPSIS
.Nm
.Op Fl -output Ar FILE
.Op diffstat-opts
.Oo
.Op Ar BASE
.Ar HEAD
.Oc
.\" SYNOPSIS }}}
.
.\" DESCRIPTION {{{
.Sh DESCRIPTION
Generate an overview of changes on a branch.
The output summarizes changes from
.Ar BASE
to
.Ar HEAD
and suggests where to pull them from.
.
.Bl -tag -width x
.It Ar BASE
"Refname" to start from.
It should be a remote-tracking branch, like
.Li upstream/stable .
If
.Ar BASE
contains a slash it's used as-is, otherwise
it's taken for a remote name and its default branch is used.
If
.Ar BASE
is omitted, the value of
.Va mantle.upstream
is used.
.It Ar HEAD
"Refname" for the top-most commit included in the request.
If
.Ar HEAD
contains a slash it's used as-is.
Otherwise, if
.Ar HEAD
is
.Qq Li HEAD
it's resolved to a branch name and qualified with the value of
.Va mantle.public .
Othersise, it's taken for a bare branch name and qualified with
the value of
.Va mantle.public .
If
.Ar HEAD
is omitted it's treated as if it was
.Qq Li HEAD .
.El
.\" DESCRIPTION }}}
.\" CONFIGURATION {{{
.Sh CONFIGURATION
.Bl -tag -width x
.It Li mantle.upstream
Default
.Ar BASE .
Defaults to
.Qq Li upstream .
.It Li mantle.public
Default remote to qualify
.Ar HEAD .
Defaults to
.Qq Li origin .
.It Li remote.${mantle.public}.url
URL used in the output to suggest pulling from.
.El
.\" CONFIGURATION }}}
.\" .Sh IMPLEMENTATION NOTES
.\" ENVIRONMENT {{{
.Sh ENVIRONMENT
.Nm
itself does not use any environment variables.
It is, however, implemented in terms of third-party commands
which
.Em do
use them.
This means
.Nm
may be influenced by environment variables used by
.Xr git 1  ,
.Xr zsh 1 ,
possibly others.
.\" ENVIRONMENT }}}
.\" FILES {{{
.\".Sh FILES
.\" FILES }}}
.\" EXAMPLES {{{
.Sh EXAMPLES
These example assume a repository with these settings in place:
.Bd -literal
% git remote add -m master upstream ...
% git remote add -m master rn ...
% git config mantle.upstream upstream
% git config mantle.public rn
.Ed
.Bl -tag -width x
.It Li % git mantle upstream/master rn/feature
Summarize the changes from
.Li upstream/master
to
.Li rn/feature ,
offering them for pull from
.Li remote.rn.url .
.
.It Li % git mantle upstream rn/feature
Summarize the changes from
.Li upstream/HEAD
to
.Li rn/feature ,
offering them for pull from
.Li remote.rn.url .
.
.It Li % git mantle rn/feature
Summarize the changes from
.Li mantle.upstream
to
.Li rn/feature ,
offering them for pull from
.Li remote.rn.url .
.
.It Li % git mantle
Summarize the changes from
.Li mantle.upstream
to the head of a branch in
.Li mantle.public ,
offering them for pull from
.Li remote.<name>.url
where
.Li <name>
is derived from
.Li mantle.public .
The branch name is derived from the active branch:
if the active branch has an upstream branch configured (in
.Li mantle.public ),
that branch is used.
If there's no upstream branch configured,
a branch eponymous with the active branch is used.
.\" EXAMPLES }}}
.\" DIAGNOSTICS {{{
.Sh DIAGNOSTICS
.Ex -std
.\" DIAGNOSTICS }}}
.\" .Sh COMPATIBILITY
.\" SEE ALSO {{{
.Sh SEE ALSO
.Bl
.It
.Xr git-request-pull 1 .
.El
.\" SEE ALSO }}}
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" AUTHORS {{{
.Sh AUTHORS
.An Roman Neuhauser Aq Mt rneuhauser@sigpipe.cz
.Lk https://github.com/roman-neuhauser/git-mantle/
.\" AUTHORS }}}
.\" BUGS {{{
.Sh BUGS
No doubt plentiful.
Please report them at
.Lk https://github.com/roman-neuhauser/git-mantle/issues
.\" BUGS }}}
